name: open-term-loan
version: 1.0.1
source: contracts
packages:
  - path: contracts/MapleLoan.sol
    contractName: MapleLoan
  - path: contracts/MapleLoanFactory.sol
    contractName: MapleLoanFactory
  - path: contracts/MapleLoanInitializer.sol
    contractName: MapleLoanInitializer
  - path: contracts/MapleRefinancer.sol
    contractName: MapleRefinancer
customDescription: Maple Open Term Loan Artifacts and ABIs
