name: open-term-loan
version: 0.0.1
source: contracts
packages:
  - path: contracts/MapleLoan.sol
    contractName: MapleLoan
  - path: contracts/MapleLoanFactory.sol
    contractName: MapleLoanFactory
  - path: contracts/MapleLoanInitializer.sol
    contractName: MapleLoanInitializer
  - path: contracts/MapleLoanStorage.sol
    contractName: MapleLoanStorage
  - path: contracts/MapleRefinancer.sol
    contractName: MapleRefinancer
customDescription: Maple Loan Artifacts and ABIs
